<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>md</string>
    </array>
    <key>foldingStartMarker</key>
    <string>(?x)
        (&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
        |&lt;!--(?!.*--&gt;)
        |\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
        )</string>
    <key>foldingStopMarker</key>
    <string>(?x)
        (&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
        |^\s*--&gt;
        |(^|\s)\}
        )</string>
    <key>name</key>
    <string>Hatena Note</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>comment</key>
            <string>
                hatena metadata
            </string>
            <key>begin</key>
            <string>^---[ \t]*$\n</string>
            <key>end</key>
            <string>^---[ \t]*$\n</string>
            <key>name</key>
            <string>meta.metadata.hatena</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>meta.separator.metadata.markdown</string>
                </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>meta.separator.metadata.markdown</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>^\s*(title|categories|Hatena-guid)\s*(:)</string>
                    <key>end</key>
                    <string>$(?=\n)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.metadata</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.separator.metadata</string>
                        </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>\w*</string>
                            <key>name</key>
                            <string>variable.other.metadata</string>
                        </dict>
                        <dict>
                            <key>begin</key>
                            <string>\[</string>
                            <key>beginCaptures</key>
                            <dict>
                                <key>0</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.definition.array.begin.json</string>
                                </dict>
                            </dict>
                            <key>end</key>
                            <string>\]</string>
                            <key>endCaptures</key>
                            <dict>
                                <key>0</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.definition.array.end.json</string>
                                </dict>
                            </dict>
                            <key>name</key>
                            <string>meta.structure.array.json</string>
                            <key>patterns</key>
                            <array>
                                <dict>
                                    <key>begin</key>
                                    <string>"</string>
                                    <key>beginCaptures</key>
                                    <dict>
                                        <key>0</key>
                                        <dict>
                                            <key>name</key>
                                            <string>punctuation.definition.string.begin.json</string>
                                        </dict>
                                    </dict>
                                    <key>end</key>
                                    <string>"</string>
                                    <key>endCaptures</key>
                                    <dict>
                                        <key>0</key>
                                        <dict>
                                            <key>name</key>
                                            <string>punctuation.definition.string.end.json</string>
                                        </dict>
                                    </dict>
                                    <key>name</key>
                                    <string>string.quoted.double.json</string>
                                    <key>patterns</key>
                                    <array>
                                        <dict>
                                            <key>match</key>
                                            <string>(?x:                # turn on extended mode
                                             \\                # a literal backslash
                                             (?:               # ...followed by...
                                               ["\\/bfnrt]     # one of these characters
                                               |               # ...or...
                                               u               # a u
                                               [0-9a-fA-F]{4}  # and four hex digits
                                             )
                                           )</string>
                                            <key>name</key>
                                            <string>constant.character.escape.json</string>
                                        </dict>
                                        <dict>
                                            <key>match</key>
                                            <string>\\.</string>
                                            <key>name</key>
                                            <string>invalid.illegal.unrecognized-string-escape.json</string>
                                        </dict>
                                    </array>
                                </dict>
                                <dict>
                                    <key>match</key>
                                    <string>,</string>
                                    <key>name</key>
                                    <string>punctuation.separator.array.json</string>
                                </dict>
                                <dict>
                                    <key>match</key>
                                    <string>[^\s\]]</string>
                                    <key>name</key>
                                    <string>invalid.illegal.expected-array-separator.json</string>
                                </dict>
                            </array>
                        </dict>
                        <dict>
                            <key>match</key>
                            <string>,</string>
                            <key>name</key>
                            <string>punctuation.separator.array.json</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>match</key>
                    <string>^[^:]+$\n</string>
                    <key>name</key>
                    <string>invalid.illegal.metadata.hatena</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>include</key>
            <string>text.html.markdown.gfm</string>
        </dict>
        <dict>
            <key>include</key>
            <string>text.html.markdown</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>text.html.markdown.hatena</string>
</dict>
</plist>
